/* tslint:disable */
/* eslint-disable */
/**
 * DevBook.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BoardDataDto,
} from '../models/index';
import {
    BoardDataDtoFromJSON,
    BoardDataDtoToJSON,
} from '../models/index';

/**
 * 
 */
export class SudokuModuleSudokuEndpointsApi extends runtime.BaseAPI {

    /**
     */
    async sudokuBoardRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BoardDataDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/sudoku`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BoardDataDtoFromJSON(jsonValue));
    }

    /**
     */
    async sudokuBoard(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BoardDataDto> {
        const response = await this.sudokuBoardRaw(initOverrides);
        return await response.value();
    }

}
