/* tslint:disable */
/* eslint-disable */
/**
 * DevBook.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BoardDataDto
 */
export interface BoardDataDto {
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof BoardDataDto
     */
    gridNumbers: Array<Array<number>>;
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof BoardDataDto
     */
    solutionNumbers: Array<Array<number>>;
}

/**
 * Check if a given object implements the BoardDataDto interface.
 */
export function instanceOfBoardDataDto(value: object): value is BoardDataDto {
    if (!('gridNumbers' in value) || value['gridNumbers'] === undefined) return false;
    if (!('solutionNumbers' in value) || value['solutionNumbers'] === undefined) return false;
    return true;
}

export function BoardDataDtoFromJSON(json: any): BoardDataDto {
    return BoardDataDtoFromJSONTyped(json, false);
}

export function BoardDataDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardDataDto {
    if (json == null) {
        return json;
    }
    return {
        
        'gridNumbers': json['gridNumbers'],
        'solutionNumbers': json['solutionNumbers'],
    };
}

export function BoardDataDtoToJSON(value?: BoardDataDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'gridNumbers': value['gridNumbers'],
        'solutionNumbers': value['solutionNumbers'],
    };
}

