/* tslint:disable */
/* eslint-disable */
/**
 * DevBook.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductType } from './ProductType';
import {
    ProductTypeFromJSON,
    ProductTypeFromJSONTyped,
    ProductTypeToJSON,
} from './ProductType';

/**
 * 
 * @export
 * @interface Book
 */
export interface Book {
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    name: string | null;
    /**
     * 
     * @type {ProductType}
     * @memberof Book
     */
    productType: ProductType;
    /**
     * 
     * @type {number}
     * @memberof Book
     */
    retailPrice: number;
    /**
     * 
     * @type {number}
     * @memberof Book
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof Book
     */
    discountAmmount: number;
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    coverImageUrl?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Book
     */
    productCategoryIds?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    authorId: string;
}

/**
 * Check if a given object implements the Book interface.
 */
export function instanceOfBook(value: object): value is Book {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('productType' in value) || value['productType'] === undefined) return false;
    if (!('retailPrice' in value) || value['retailPrice'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('discountAmmount' in value) || value['discountAmmount'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    return true;
}

export function BookFromJSON(json: any): Book {
    return BookFromJSONTyped(json, false);
}

export function BookFromJSONTyped(json: any, ignoreDiscriminator: boolean): Book {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'productType': ProductTypeFromJSON(json['productType']),
        'retailPrice': json['retailPrice'],
        'price': json['price'],
        'discountAmmount': json['discountAmmount'],
        'description': json['description'] == null ? undefined : json['description'],
        'coverImageUrl': json['coverImageUrl'] == null ? undefined : json['coverImageUrl'],
        'productCategoryIds': json['productCategoryIds'] == null ? undefined : json['productCategoryIds'],
        'authorId': json['authorId'],
    };
}

export function BookToJSON(value?: Book | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'productType': ProductTypeToJSON(value['productType']),
        'retailPrice': value['retailPrice'],
        'price': value['price'],
        'discountAmmount': value['discountAmmount'],
        'description': value['description'],
        'coverImageUrl': value['coverImageUrl'],
        'productCategoryIds': value['productCategoryIds'],
        'authorId': value['authorId'],
    };
}

