/* tslint:disable */
/* eslint-disable */
/**
 * DevBook.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProductCategoryCommand
 */
export interface CreateProductCategoryCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateProductCategoryCommand
     */
    name: string;
}

/**
 * Check if a given object implements the CreateProductCategoryCommand interface.
 */
export function instanceOfCreateProductCategoryCommand(value: object): value is CreateProductCategoryCommand {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateProductCategoryCommandFromJSON(json: any): CreateProductCategoryCommand {
    return CreateProductCategoryCommandFromJSONTyped(json, false);
}

export function CreateProductCategoryCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProductCategoryCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateProductCategoryCommandToJSON(value?: CreateProductCategoryCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

