/* tslint:disable */
/* eslint-disable */
/**
 * DevBook.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProjectInput
 */
export interface CreateProjectInput {
    /**
     * 
     * @type {string}
     * @memberof CreateProjectInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProjectInput
     */
    details?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateProjectInput
     */
    hourlyRate?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateProjectInput
     */
    currency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateProjectInput
     */
    hexColor?: string | null;
}

/**
 * Check if a given object implements the CreateProjectInput interface.
 */
export function instanceOfCreateProjectInput(value: object): value is CreateProjectInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateProjectInputFromJSON(json: any): CreateProjectInput {
    return CreateProjectInputFromJSONTyped(json, false);
}

export function CreateProjectInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'details': json['details'] == null ? undefined : json['details'],
        'hourlyRate': json['hourlyRate'] == null ? undefined : json['hourlyRate'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'hexColor': json['hexColor'] == null ? undefined : json['hexColor'],
    };
}

export function CreateProjectInputToJSON(value?: CreateProjectInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'details': value['details'],
        'hourlyRate': value['hourlyRate'],
        'currency': value['currency'],
        'hexColor': value['hexColor'],
    };
}

