/* tslint:disable */
/* eslint-disable */
/**
 * DevBook.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBookCommand
 */
export interface CreateBookCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateBookCommand
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBookCommand
     */
    authorId: string;
    /**
     * 
     * @type {number}
     * @memberof CreateBookCommand
     */
    retailPrice: number;
    /**
     * 
     * @type {number}
     * @memberof CreateBookCommand
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof CreateBookCommand
     */
    discountAmmount: number;
    /**
     * 
     * @type {string}
     * @memberof CreateBookCommand
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateBookCommand
     */
    coverImageUrl?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateBookCommand
     */
    productCategoryIds?: Array<string> | null;
}

/**
 * Check if a given object implements the CreateBookCommand interface.
 */
export function instanceOfCreateBookCommand(value: object): value is CreateBookCommand {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    if (!('retailPrice' in value) || value['retailPrice'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('discountAmmount' in value) || value['discountAmmount'] === undefined) return false;
    return true;
}

export function CreateBookCommandFromJSON(json: any): CreateBookCommand {
    return CreateBookCommandFromJSONTyped(json, false);
}

export function CreateBookCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBookCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'authorId': json['authorId'],
        'retailPrice': json['retailPrice'],
        'price': json['price'],
        'discountAmmount': json['discountAmmount'],
        'description': json['description'] == null ? undefined : json['description'],
        'coverImageUrl': json['coverImageUrl'] == null ? undefined : json['coverImageUrl'],
        'productCategoryIds': json['productCategoryIds'] == null ? undefined : json['productCategoryIds'],
    };
}

export function CreateBookCommandToJSON(value?: CreateBookCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'authorId': value['authorId'],
        'retailPrice': value['retailPrice'],
        'price': value['price'],
        'discountAmmount': value['discountAmmount'],
        'description': value['description'],
        'coverImageUrl': value['coverImageUrl'],
        'productCategoryIds': value['productCategoryIds'],
    };
}

