/* tslint:disable */
/* eslint-disable */
/**
 * DevBook.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWorkTaskInput
 */
export interface CreateWorkTaskInput {
    /**
     * 
     * @type {string}
     * @memberof CreateWorkTaskInput
     */
    projectId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkTaskInput
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkTaskInput
     */
    details?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CreateWorkTaskInput
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkTaskInput
     */
    start: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkTaskInput
     */
    end: string;
}

/**
 * Check if a given object implements the CreateWorkTaskInput interface.
 */
export function instanceOfCreateWorkTaskInput(value: object): value is CreateWorkTaskInput {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    return true;
}

export function CreateWorkTaskInputFromJSON(json: any): CreateWorkTaskInput {
    return CreateWorkTaskInputFromJSONTyped(json, false);
}

export function CreateWorkTaskInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkTaskInput {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'description': json['description'] == null ? undefined : json['description'],
        'details': json['details'] == null ? undefined : json['details'],
        'date': (new Date(json['date'])),
        'start': json['start'],
        'end': json['end'],
    };
}

export function CreateWorkTaskInputToJSON(value?: CreateWorkTaskInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'projectId': value['projectId'],
        'description': value['description'],
        'details': value['details'],
        'date': ((value['date']).toISOString()),
        'start': value['start'],
        'end': value['end'],
    };
}

