/* tslint:disable */
/* eslint-disable */
/**
 * DevBook.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchProjectCommandDto
 */
export interface PatchProjectCommandDto {
    /**
     * 
     * @type {string}
     * @memberof PatchProjectCommandDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchProjectCommandDto
     */
    details?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchProjectCommandDto
     */
    hourlyRate?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchProjectCommandDto
     */
    currency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchProjectCommandDto
     */
    hexColor?: string | null;
}

/**
 * Check if a given object implements the PatchProjectCommandDto interface.
 */
export function instanceOfPatchProjectCommandDto(value: object): value is PatchProjectCommandDto {
    return true;
}

export function PatchProjectCommandDtoFromJSON(json: any): PatchProjectCommandDto {
    return PatchProjectCommandDtoFromJSONTyped(json, false);
}

export function PatchProjectCommandDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchProjectCommandDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'details': json['details'] == null ? undefined : json['details'],
        'hourlyRate': json['hourlyRate'] == null ? undefined : json['hourlyRate'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'hexColor': json['hexColor'] == null ? undefined : json['hexColor'],
    };
}

export function PatchProjectCommandDtoToJSON(value?: PatchProjectCommandDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'details': value['details'],
        'hourlyRate': value['hourlyRate'],
        'currency': value['currency'],
        'hexColor': value['hexColor'],
    };
}

