/* tslint:disable */
/* eslint-disable */
/**
 * DevBook.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchAuthorCommandDto
 */
export interface PatchAuthorCommandDto {
    /**
     * 
     * @type {string}
     * @memberof PatchAuthorCommandDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchAuthorCommandDto
     */
    description?: string | null;
}

/**
 * Check if a given object implements the PatchAuthorCommandDto interface.
 */
export function instanceOfPatchAuthorCommandDto(value: object): value is PatchAuthorCommandDto {
    return true;
}

export function PatchAuthorCommandDtoFromJSON(json: any): PatchAuthorCommandDto {
    return PatchAuthorCommandDtoFromJSONTyped(json, false);
}

export function PatchAuthorCommandDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchAuthorCommandDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function PatchAuthorCommandDtoToJSON(value?: PatchAuthorCommandDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

