/* tslint:disable */
/* eslint-disable */
/**
 * DevBook.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchBookCommandDto
 */
export interface PatchBookCommandDto {
    /**
     * 
     * @type {string}
     * @memberof PatchBookCommandDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchBookCommandDto
     */
    authorId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchBookCommandDto
     */
    retailPrice?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchBookCommandDto
     */
    price?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchBookCommandDto
     */
    discountAmmount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchBookCommandDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchBookCommandDto
     */
    coverImageUrl?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchBookCommandDto
     */
    productCategoryIds?: Array<string> | null;
}

/**
 * Check if a given object implements the PatchBookCommandDto interface.
 */
export function instanceOfPatchBookCommandDto(value: object): value is PatchBookCommandDto {
    return true;
}

export function PatchBookCommandDtoFromJSON(json: any): PatchBookCommandDto {
    return PatchBookCommandDtoFromJSONTyped(json, false);
}

export function PatchBookCommandDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchBookCommandDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
        'retailPrice': json['retailPrice'] == null ? undefined : json['retailPrice'],
        'price': json['price'] == null ? undefined : json['price'],
        'discountAmmount': json['discountAmmount'] == null ? undefined : json['discountAmmount'],
        'description': json['description'] == null ? undefined : json['description'],
        'coverImageUrl': json['coverImageUrl'] == null ? undefined : json['coverImageUrl'],
        'productCategoryIds': json['productCategoryIds'] == null ? undefined : json['productCategoryIds'],
    };
}

export function PatchBookCommandDtoToJSON(value?: PatchBookCommandDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'authorId': value['authorId'],
        'retailPrice': value['retailPrice'],
        'price': value['price'],
        'discountAmmount': value['discountAmmount'],
        'description': value['description'],
        'coverImageUrl': value['coverImageUrl'],
        'productCategoryIds': value['productCategoryIds'],
    };
}

