/* tslint:disable */
/* eslint-disable */
/**
 * DevBook.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Book } from './Book';
import {
    instanceOfBook,
    BookFromJSON,
    BookFromJSONTyped,
    BookToJSON,
} from './Book';

/**
 * @type ProductsGetAll200ResponseInner
 * 
 * @export
 */
export type ProductsGetAll200ResponseInner = Book;

export function ProductsGetAll200ResponseInnerFromJSON(json: any): ProductsGetAll200ResponseInner {
    return ProductsGetAll200ResponseInnerFromJSONTyped(json, false);
}

export function ProductsGetAll200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductsGetAll200ResponseInner {
    if (json == null) {
        return json;
    }
    if (instanceOfBook(json)) {
        return BookFromJSONTyped(json, true);
    }
}

export function ProductsGetAll200ResponseInnerToJSON(value?: ProductsGetAll200ResponseInner | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfBook(value)) {
        return BookToJSON(value as Book);
    }

    return {};
}

