/* tslint:disable */
/* eslint-disable */
/**
 * DevBook.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResendConfirmationEmailRequest
 */
export interface ResendConfirmationEmailRequest {
    /**
     * 
     * @type {string}
     * @memberof ResendConfirmationEmailRequest
     */
    email: string | null;
}

/**
 * Check if a given object implements the ResendConfirmationEmailRequest interface.
 */
export function instanceOfResendConfirmationEmailRequest(value: object): value is ResendConfirmationEmailRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function ResendConfirmationEmailRequestFromJSON(json: any): ResendConfirmationEmailRequest {
    return ResendConfirmationEmailRequestFromJSONTyped(json, false);
}

export function ResendConfirmationEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResendConfirmationEmailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function ResendConfirmationEmailRequestToJSON(value?: ResendConfirmationEmailRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
    };
}

