/* tslint:disable */
/* eslint-disable */
/**
 * DevBook.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartWorkTaskInput
 */
export interface StartWorkTaskInput {
    /**
     * 
     * @type {string}
     * @memberof StartWorkTaskInput
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof StartWorkTaskInput
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof StartWorkTaskInput
     */
    start: string;
}

/**
 * Check if a given object implements the StartWorkTaskInput interface.
 */
export function instanceOfStartWorkTaskInput(value: object): value is StartWorkTaskInput {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    return true;
}

export function StartWorkTaskInputFromJSON(json: any): StartWorkTaskInput {
    return StartWorkTaskInputFromJSONTyped(json, false);
}

export function StartWorkTaskInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartWorkTaskInput {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'date': (new Date(json['date'])),
        'start': json['start'],
    };
}

export function StartWorkTaskInputToJSON(value?: StartWorkTaskInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'date': ((value['date']).toISOString()),
        'start': value['start'],
    };
}

