/* tslint:disable */
/* eslint-disable */
/**
 * DevBook.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProjectCommandDto
 */
export interface UpdateProjectCommandDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectCommandDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectCommandDto
     */
    details?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateProjectCommandDto
     */
    hourlyRate?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectCommandDto
     */
    currency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectCommandDto
     */
    hexColor?: string | null;
}

/**
 * Check if a given object implements the UpdateProjectCommandDto interface.
 */
export function instanceOfUpdateProjectCommandDto(value: object): value is UpdateProjectCommandDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateProjectCommandDtoFromJSON(json: any): UpdateProjectCommandDto {
    return UpdateProjectCommandDtoFromJSONTyped(json, false);
}

export function UpdateProjectCommandDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProjectCommandDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'details': json['details'] == null ? undefined : json['details'],
        'hourlyRate': json['hourlyRate'] == null ? undefined : json['hourlyRate'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'hexColor': json['hexColor'] == null ? undefined : json['hexColor'],
    };
}

export function UpdateProjectCommandDtoToJSON(value?: UpdateProjectCommandDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'details': value['details'],
        'hourlyRate': value['hourlyRate'],
        'currency': value['currency'],
        'hexColor': value['hexColor'],
    };
}

