/* tslint:disable */
/* eslint-disable */
/**
 * DevBook.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAuthorCommandDto
 */
export interface UpdateAuthorCommandDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateAuthorCommandDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAuthorCommandDto
     */
    description?: string | null;
}

/**
 * Check if a given object implements the UpdateAuthorCommandDto interface.
 */
export function instanceOfUpdateAuthorCommandDto(value: object): value is UpdateAuthorCommandDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateAuthorCommandDtoFromJSON(json: any): UpdateAuthorCommandDto {
    return UpdateAuthorCommandDtoFromJSONTyped(json, false);
}

export function UpdateAuthorCommandDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAuthorCommandDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function UpdateAuthorCommandDtoToJSON(value?: UpdateAuthorCommandDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

