/* tslint:disable */
/* eslint-disable */
/**
 * DevBook.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkTaskDto } from './WorkTaskDto';
import {
    WorkTaskDtoFromJSON,
    WorkTaskDtoFromJSONTyped,
    WorkTaskDtoToJSON,
} from './WorkTaskDto';

/**
 * 
 * @export
 * @interface WorkTaskListResponse
 */
export interface WorkTaskListResponse {
    /**
     * 
     * @type {WorkTaskDto}
     * @memberof WorkTaskListResponse
     */
    activeWorkTask?: WorkTaskDto | null;
    /**
     * 
     * @type {{ [key: string]: Array<WorkTaskDto>; }}
     * @memberof WorkTaskListResponse
     */
    workTasksInDay?: { [key: string]: Array<WorkTaskDto>; } | null;
}

/**
 * Check if a given object implements the WorkTaskListResponse interface.
 */
export function instanceOfWorkTaskListResponse(value: object): value is WorkTaskListResponse {
    return true;
}

export function WorkTaskListResponseFromJSON(json: any): WorkTaskListResponse {
    return WorkTaskListResponseFromJSONTyped(json, false);
}

export function WorkTaskListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkTaskListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'activeWorkTask': json['activeWorkTask'] == null ? undefined : WorkTaskDtoFromJSON(json['activeWorkTask']),
        'workTasksInDay': json['workTasksInDay'] == null ? undefined : json['workTasksInDay'],
    };
}

export function WorkTaskListResponseToJSON(value?: WorkTaskListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'activeWorkTask': WorkTaskDtoToJSON(value['activeWorkTask']),
        'workTasksInDay': value['workTasksInDay'],
    };
}

