/* tslint:disable */
/* eslint-disable */
/**
 * DevBook.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectDto } from './ProjectDto';
import {
    ProjectDtoFromJSON,
    ProjectDtoFromJSONTyped,
    ProjectDtoToJSON,
} from './ProjectDto';

/**
 * 
 * @export
 * @interface WorkTaskDto
 */
export interface WorkTaskDto {
    /**
     * 
     * @type {string}
     * @memberof WorkTaskDto
     */
    id: string;
    /**
     * 
     * @type {ProjectDto}
     * @memberof WorkTaskDto
     */
    project?: ProjectDto | null;
    /**
     * 
     * @type {string}
     * @memberof WorkTaskDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WorkTaskDto
     */
    details?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof WorkTaskDto
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof WorkTaskDto
     */
    start: string;
    /**
     * 
     * @type {string}
     * @memberof WorkTaskDto
     */
    end?: string | null;
}

/**
 * Check if a given object implements the WorkTaskDto interface.
 */
export function instanceOfWorkTaskDto(value: object): value is WorkTaskDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    return true;
}

export function WorkTaskDtoFromJSON(json: any): WorkTaskDto {
    return WorkTaskDtoFromJSONTyped(json, false);
}

export function WorkTaskDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkTaskDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'project': json['project'] == null ? undefined : ProjectDtoFromJSON(json['project']),
        'description': json['description'] == null ? undefined : json['description'],
        'details': json['details'] == null ? undefined : json['details'],
        'date': (new Date(json['date'])),
        'start': json['start'],
        'end': json['end'] == null ? undefined : json['end'],
    };
}

export function WorkTaskDtoToJSON(value?: WorkTaskDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'project': ProjectDtoToJSON(value['project']),
        'description': value['description'],
        'details': value['details'],
        'date': ((value['date']).toISOString()),
        'start': value['start'],
        'end': value['end'],
    };
}

